import{cleanup,fireEvent,render,screen,waitFor}from'@testing-library/react';
import{afterEach,beforeEach,describe,expect,it,vi}from'vitest';
import{I18nProvider}from'../lib/i18n';
import{ApiError}from'../lib/api';
import{ModelSettingsDialog}from'./ModelSettingsDialog';

const apiMock=vi.hoisted(()=>({aiSettings:vi.fn(),validateAISettings:vi.fn(),saveAISettings:vi.fn(),resetAISettings:vi.fn()}));
vi.mock('../lib/api',()=>({api:apiMock,ApiError:class ApiError extends Error{constructor(message:string,public status:number,public code?:string,public runId?:string|number,public diagnostics?:unknown){super(message)}}}));
function view(onSaved=vi.fn()){return render(<I18nProvider><ModelSettingsDialog onClose={vi.fn()} onSaved={onSaved}/></I18nProvider>)}

beforeEach(()=>{localStorage.clear();localStorage.setItem('cw.locale','zh-CN');apiMock.aiSettings.mockResolvedValue({configured:true,provider:'openai-compatible',baseUrl:'http://localhost:1234/v1',model:'私有模型',systemPrompt:'',hasApiKey:true,source:'runtime',persistence:'memory',networkMode:'auto',apiKeyPersisted:false,secureKeyStorageAvailable:true,credentialError:false,secretPersistence:'memory'});apiMock.validateAISettings.mockResolvedValue({ok:true,modelCount:2,selectedModelAvailable:true,models:['私有模型','另一个模型'],diagnostics:{requestedMode:'auto',routeUsed:'direct',attempts:[{route:'direct',outcome:'connected',durationMs:24}]}});apiMock.saveAISettings.mockResolvedValue({configured:true})});
afterEach(()=>{cleanup();vi.clearAllMocks()});

describe('model settings',()=>{
 it('renders bilingual chrome and an accessible SVG close action without ever rendering the stored secret',async()=>{view();expect(await screen.findByDisplayValue('私有模型')).toBeInTheDocument();const close=screen.getByRole('button',{name:'关闭'});expect(close).toHaveClass('icon-button');expect(close.querySelector('svg')).not.toBeNull();expect(close).not.toHaveTextContent('×');expect(screen.queryByDisplayValue(/secret|sk-/i)).not.toBeInTheDocument();expect(screen.getByPlaceholderText('留空将保留已有密钥')).toHaveValue('');fireEvent.change(screen.getByDisplayValue('中文'),{target:{value:'en'}});expect(screen.getByText('Model settings')).toBeInTheDocument();expect(screen.getByDisplayValue('私有模型')).toBeInTheDocument()});
 it('validates without saving and populates the model choices',async()=>{view();fireEvent.click(await screen.findByRole('button',{name:'测试并获取模型'}));await waitFor(()=>expect(apiMock.validateAISettings).toHaveBeenCalledTimes(1));expect(apiMock.saveAISettings).not.toHaveBeenCalled();expect(document.querySelector('option[value="另一个模型"]')).not.toBeNull();expect(screen.getByText('连接成功，已加载模型列表。')).toBeInTheDocument()});
 it('discovers models when the model field is blank but keeps Save disabled',async()=>{apiMock.aiSettings.mockResolvedValue({...await apiMock.aiSettings(),model:''});view();const test=await screen.findByRole('button',{name:'测试并获取模型'}),save=screen.getByRole('button',{name:'保存'});expect(test).toBeEnabled();expect(save).toBeDisabled();fireEvent.click(test);await waitFor(()=>expect(apiMock.validateAISettings).toHaveBeenCalledWith(expect.objectContaining({model:''})));expect(document.querySelector('option[value="私有模型"]')).not.toBeNull()});
 it('explains provider timeouts without exposing low-level transport text',async()=>{apiMock.validateAISettings.mockRejectedValueOnce(new ApiError('Unable to connect to the model provider',504,'modelDiscoveryTimeout'));view();fireEvent.click(await screen.findByRole('button',{name:'测试并获取模型'}));expect(await screen.findByText('连接失败: 模型服务连接超时。')).toBeInTheDocument();expect(screen.getByText('如果服务商不提供 /models 接口，可以手动填写准确模型 ID 后直接保存。')).toBeInTheDocument()});
 it('saves non-secret settings without a model-response timeout',async()=>{const refreshed=vi.fn();view(refreshed);expect(screen.queryByLabelText('超时（秒）')).not.toBeInTheDocument();fireEvent.click(await screen.findByRole('button',{name:'保存'}));await waitFor(()=>expect(apiMock.saveAISettings).toHaveBeenCalledWith(expect.objectContaining({baseUrl:'http://localhost:1234/v1',model:'私有模型',persistence:'memory'})));const saved=apiMock.saveAISettings.mock.calls[0][0];expect(saved).not.toHaveProperty('apiKey');expect(saved).not.toHaveProperty('timeoutSeconds');expect(saved).not.toHaveProperty('connectTimeoutSeconds');expect(refreshed).toHaveBeenCalledTimes(1)});
 it('keeps an unfinished non-secret draft when the dialog is reopened',async()=>{const first=view();const base=await screen.findByDisplayValue('http://localhost:1234/v1');fireEvent.change(base,{target:{value:'http://localhost:11434/v1'}});fireEvent.change(screen.getByDisplayValue('私有模型'),{target:{value:'llama3'}});first.unmount();apiMock.aiSettings.mockResolvedValue({...await apiMock.aiSettings(),baseUrl:'https://provider.example/v1',model:'server-default'});view();expect(await screen.findByDisplayValue('http://localhost:11434/v1')).toBeInTheDocument();expect(screen.getByDisplayValue('llama3')).toBeInTheDocument()});
 it('shows route diagnostics and opts into encrypted key persistence explicitly',async()=>{view();expect(await screen.findByText('自动模式先尝试直连；只有连接无法建立时，才尝试系统代理。')).toBeInTheDocument();fireEvent.click(screen.getByLabelText(/为当前 Windows 账户安全保存 API 密钥/));fireEvent.click(screen.getByRole('button',{name:'测试并获取模型'}));expect(await screen.findByText('24 ms')).toBeInTheDocument();expect(screen.getAllByText('直连')).toHaveLength(2);fireEvent.click(screen.getByRole('button',{name:'保存'}));await waitFor(()=>expect(apiMock.saveAISettings).toHaveBeenCalledWith(expect.objectContaining({persistence:'local',persistApiKey:true,networkMode:'auto'})))});
});
