import{useEffect,useMemo,useRef,type MouseEvent}from'react';
import{Background,Controls,Handle,MarkerType,MiniMap,Position,ReactFlow,type Node,type NodeProps}from'@xyflow/react';
import'@xyflow/react/dist/style.css';import type{Graph,Instance}from'../domain/types';import{graphEdges,memoryPath}from'../domain/graph';
type ConversationData={instance:Instance;active:boolean;onSelect:(id:string)=>void;onActivate:(id:string)=>void};
function layout(graph:Graph,onSelect:(id:string)=>void,onActivate:(id:string)=>void){const depths=new Map<string,number>();const map=new Map(graph.nodes.map(n=>[n.id,n]));const depth=(n:Instance):number=>{if(depths.has(n.id))return depths.get(n.id)!;const d=n.parentId&&map.has(n.parentId)?depth(map.get(n.parentId)!)+1:0;depths.set(n.id,d);return d};const rows=new Map<number,number>();return graph.nodes.map(n=>{const d=depth(n),r=rows.get(d)||0;rows.set(d,r+1);return{id:n.id,type:'conversation',position:{x:40+d*310,y:40+r*130},data:{instance:n,active:n.id===graph.activeInstanceId,onSelect,onActivate}}})}
export function nodeSubtitle(instance:Instance){return instance.summary?.trim()||''}
export function shouldShowMiniMap(nodeCount:number){return nodeCount>=8}
const SINGLE_CLICK_DELAY_MS=240;
export function useClickArbitration(onSingle:()=>void,onDouble:()=>void){const timer=useRef<ReturnType<typeof setTimeout>|null>(null),handledDouble=useRef(false);const cancel=()=>{if(timer.current!==null){clearTimeout(timer.current);timer.current=null}};useEffect(()=>cancel,[]);return{onClick:(event:MouseEvent)=>{event.stopPropagation();cancel();if(event.detail>=2){handledDouble.current=true;onDouble();return}handledDouble.current=false;timer.current=setTimeout(()=>{timer.current=null;onSingle()},SINGLE_CLICK_DELAY_MS)},onDoubleClick:(event:MouseEvent)=>{event.preventDefault();event.stopPropagation();cancel();if(handledDouble.current){handledDouble.current=false;return}onDouble()}}}
export function ConversationCard({data,selected=false}:{data:ConversationData;selected?:boolean}){const n=data.instance,subtitle=nodeSubtitle(n),events=useClickArbitration(()=>data.onSelect(n.id),()=>data.onActivate(n.id));return <div className={`flow-node ${data.active?'is-active':''} ${n.status==='pruned'?'is-pruned':''} ${selected?'is-selected':''}`} data-instance-id={n.id} {...events}><strong>{n.title}</strong>{subtitle&&<span>{subtitle}</span>}</div>}
function ConversationNode({data,selected}:NodeProps<Node<ConversationData>>){return <><Handle type="target" position={Position.Left}/><ConversationCard data={data} selected={selected}/><Handle type="source" position={Position.Right}/></>}
const nodeTypes={conversation:ConversationNode};
export function reactFlowNodePointerProps(onActivate:(id:string)=>void){return{onNodeClick:()=>{},onNodeDoubleClick:(_event:MouseEvent,node:Node)=>onActivate(node.id)}}
export function WorkflowGraph({graph,selectedId,onSelect,onActivate}:{graph:Graph;selectedId:string;onSelect:(id:string)=>void;onActivate:(id:string)=>void}){const nodes=useMemo(()=>layout(graph,onSelect,onActivate).map(n=>({...n,selected:n.id===selectedId})),[graph,selectedId,onSelect,onActivate]);const edges=useMemo(()=>graphEdges(graph).map(e=>({...e,type:'smoothstep',markerEnd:{type:MarkerType.ArrowClosed}})),[graph]);const wrapperEvents=useMemo(()=>reactFlowNodePointerProps(onActivate),[onActivate]);/* NodeWrapper is the reliable native dblclick target. Card dblclick stops propagation, so either the card or wrapper activates, never both. */return <ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView nodesDraggable={false} nodesConnectable={false} elementsSelectable={false} {...wrapperEvents}><Background gap={16} size={1}/>{shouldShowMiniMap(nodes.length)&&<MiniMap/>}<Controls/></ReactFlow>}
export function pathTitles(graph:Graph,id:string){return memoryPath(graph,id).map(n=>n.title)}
