export type Status='active'|'pruned'|'creating'|'error';
export interface WorkflowSummary {id:string;name:string;activeInstanceId?:string}
export interface Instance {id:string;workflowId?:string;parentId:string|null;topicId:string;title:string;titleGenerated?:boolean;summary?:string;status:Status;provider?:string;contentRevision?:number}
export interface Graph {workflowId:string;name:string;rootInstanceId:string;activeInstanceId:string|null;activeRouteInstanceId?:string|null;activeRouteTitle?:string|null;activeRouteContentRevision?:number;graphRevision:number;eventRevision:number;nodes:Instance[]}
export interface ChatResponseDetails {durationMs:number;provider?:string|null;model?:string|null;inputTokens?:number|null;outputTokens?:number|null;cachedInputTokens?:number|null;uncachedInputTokens?:number|null;cacheReuseRatio?:number|null;cacheCoverage?:number|null;cacheStatus?:'reported'|'not_reported'|'unsupported'|'invalid';sources?:AttachmentSource[];retrievalPlan?:RetrievalPlan|null;compactionPlan?:CompactionPlan|null}
export interface Message {id:string|number;role:'user'|'assistant'|'system'|'tool';content:string;createdAt?:string;inherited?:boolean;contentRevision?:number;graphRevision?:number;responseDetails?:ChatResponseDetails}
export interface MessageSnapshot {messages:Message[];contentRevision:number;eventRevision?:number}
export interface AttachmentSource {attachmentId?:string;name?:string;chunkOrdinal:number;locator:string;chunkSha256?:string;routeInstanceId?:string;routeTitle?:string;inherited?:boolean;retrievalMode?:'explicit'|'automatic';characters?:number;includedCharacters?:number;score?:number;matchedTerms?:string[];reason?:string}
export interface RetrievalPlan {planVersion:number;mode:'automatic';query:string;engine:string;budgetCharacters:number;candidateCount:number;selectedCharacters:number;selectedChunks:number;truncated:boolean;routeInstanceIds:string[];contextSha256:string;sources:AttachmentSource[]}
export interface CompactionPlan {planVersion:number;mode:'automatic';compactorVersion:string;targetInstanceId:string|null;routeInstanceIds:string[];prefixRouteInstanceIds:string[];routeRevisionVector:Array<{instanceId:string;contentRevision:number}>;budgetCharacters:number;originalCharacters:number;resultCharacters:number;originalMessages:number;compactedMessages:number;retainedMessages:number;summaryCharacters:number;sourceMessageIds:Array<string|number>;sourceMessageSetSha256:string;summarySha256:string;contextSha256:string;compressionRatio:number;budgetExceededByProtectedTail:boolean}
export interface AttachmentChunk {ordinal:number;locator:string;characters:number;preview:string}
export interface UploadedAttachment {attachmentId:string;name:string;mimeType:string;size:number;sha256:string;status:'uploaded'|'bound';parseStatus:'processing'|'ready'|'failed';parser:string|null;parseErrorCode:string|null;parseError:string|null;extractedCharacters:number;chunkCount:number;contextCharacters:number;contextTruncated:boolean;contextSources:AttachmentSource[];messageId?:string|number|null;routeInstanceId?:string;routeTitle?:string|null;inherited?:boolean;createdAt?:string;boundAt?:string|null;chunks?:AttachmentChunk[]}
export interface AttachmentUploadSession {uploadId:string;workflowId:string;instanceId:string;name:string;mimeType:string;size:number;chunkSize:number;totalChunks:number;receivedChunks:number[];missingChunks:number[];status:'uploading'|'assembling'|'completed'|'cancelled';attachmentId:string|null;createdAt?:string;updatedAt?:string}
export interface AttachmentSearchResult {attachmentId:string;name:string;routeInstanceId:string;routeTitle:string;inherited:boolean;chunkOrdinal:number;locator:string;characters:number;score:number;chunkSha256?:string;preview:string}
export interface AttachmentSearchStatus {workflowId:string;instanceId:string;engine:'fts5-trigram';indexVersion:number;ready:boolean;indexedChunks:number;readyChunks:number}
export interface ContextPreview {workflowId:string;instanceId:string;memoryRoute:Array<{instanceId:string;topicId?:string;title:string;contentRevision?:number;source?:string}>;messages:Array<Message & {sourceInstanceId:string;sourceTitle:string}>;messageCount:number;inheritedMessageCount:number;localMessageCount:number;contentRevision:number;eventRevision:number;contextSha256:string;estimatedCharacters:number;estimatedTokens:number;truncated:boolean;checkpoint:Record<string,unknown>|null;acceptedKnowledge?:KnowledgeItem[];runtimeSource?:string}
export interface TurnMemoryRouteNode {instanceId:string;title:string}
export interface TurnRouteNode {routeInstanceId:string;title:string;titleGenerated?:boolean;parentRouteInstanceId:string|null;anchorMessageId:number|null;checkpointAnchor:Record<string,unknown>|null;contentRevision:number;memoryRoute:TurnMemoryRouteNode[];inheritedMessageCount:number;createdAt?:string;updatedAt?:string}
export type ConversationTurnStatus='completed'|'pending'|'running'|'failed'|'interrupted';
export interface ConversationTurn {id:string;sequence:number;anchorMessageId:number;userMessage:Message;responses:Message[];status:ConversationTurnStatus;routeInstanceId?:string;routeTitle?:string;parentTurnId?:string|null}
export interface TurnCanvasSnapshot {workflowId:string;instanceId:string;ownerInstanceId?:string;activeRouteInstanceId?:string;scope:'local';contentRevision:number;eventRevision:number;memoryRoute:TurnMemoryRouteNode[];inheritedMessageCount:number;checkpointAnchor:Record<string,unknown>|null;preamble:Message[];turns:ConversationTurn[];eventExtensions:unknown[];routeContentRevisions?:Record<string,number>;routeMemoryRoutes?:Record<string,TurnMemoryRouteNode[]>;routeInheritedMessageCounts?:Record<string,number>;routeTitles?:Record<string,string>;routeNodes?:TurnRouteNode[]}
export interface Route {id:string;topicId:string;title:string;memoryRoute:string[];status:Status}
export interface PrunePlan {graphRevision:number;targetInstanceId?:string;nodes:Array<{id:string;title?:string}>;rootRemoval?:boolean}
export type NetworkMode='auto'|'system'|'direct';
export type ReasoningEffort='low'|'medium'|'high'|'xhigh';
export type NetworkRoute='system'|'direct';
export interface ConnectionAttempt {route:NetworkRoute;outcome:'connected'|'connection-error'|'http-error'|'invalid-response';category?:'dns'|'tls'|'proxy'|'timeout'|'connection';durationMs:number;httpStatus?:number}
export interface ConnectionDiagnostics {requestedMode:NetworkMode;routeUsed:NetworkRoute|null;attempts:ConnectionAttempt[]}
export interface ApiErrorPayload {message?:string;error?:string;code?:string;runId?:string|number;diagnostics?:ConnectionDiagnostics}
export interface AIStatus {configured:boolean;provider:string;model:string|null;reasoningEffort?:ReasoningEffort|null;reason?:string|null}
export interface AISettings extends AIStatus {baseUrl:string|null;systemPrompt:string;hasApiKey:boolean;source:string;persistence:'memory'|'local';networkMode:NetworkMode;apiKeyPersisted:boolean;secureKeyStorageAvailable:boolean;credentialError:boolean;secretPersistence:'environment'|'secure-local'|'memory'|'none'}
export interface AISettingsInput {baseUrl:string;model:string;apiKey?:string;systemPrompt?:string;persistence:'memory'|'local';clearApiKey?:boolean;persistApiKey?:boolean;networkMode?:NetworkMode;reasoningEffort?:ReasoningEffort|null}
export interface AIValidation {ok:boolean;modelCount:number;selectedModelAvailable:boolean;models:string[];diagnostics:ConnectionDiagnostics}
export type AgentRunStatus='queued'|'running'|'awaiting_approval'|'cancelling'|'cancelled'|'completed'|'failed'|'interrupted'|'unknown';
export interface AgentToolSpec {name:string;version:string;description?:string}
export interface AgentMemoryRouteNode {instanceId:string;topicId:string;title:string}
export interface KnowledgeItem {knowledgeItemId:string;kind:'conclusion'|'decision'|'fact'|'constraint';title:string;content:string;provenance:Record<string,unknown>}
export type AgentApprovalStatus='pending'|'approved'|'rejected';
export interface AgentApprovalRequest {approvalId:string;runId?:string|number;toolCallId?:string;toolName:string;toolVersion?:string;arguments?:unknown;sideEffect?:boolean|string;status:AgentApprovalStatus;createdAt?:string;decidedAt?:string|null}
export interface AgentRunMetrics {durationMs:number|null;modelStepCount:number;toolCallCount:number;toolDurationMs:number;inputTokens:number|null;outputTokens:number|null;estimatedCost:number|null;cachedInputTokens?:number|null;uncachedInputTokens?:number|null;cacheReuseRatio?:number|null;cacheCoverage?:number|null;cacheStatus?:'reported'|'not_reported'|'unsupported'|'invalid'}
export interface AgentRun {runId:string|number;workflowId:string;instanceId:string;status:AgentRunStatus;inputContentRevision:number;attemptNumber?:number;rootRunId?:string|number;parentRunId?:string|number|null;executionPhase?:string|null;leaseExpiresAt?:string|null;lastHeartbeatAt?:string|null;contextSha256?:string;modelSnapshot?:unknown;memoryRoute?:AgentMemoryRouteNode[];acceptedKnowledge?:KnowledgeItem[];retrievalPlan?:RetrievalPlan|null;compactionPlan?:CompactionPlan|null;availableTools?:AgentToolSpec[];approvalRequests?:AgentApprovalRequest[];artifacts?:Artifact[];objective:string;constraints:string[];deliverables:string[];acceptanceChecks:string[];finalMessageId?:string|number|null;finalAnswer?:string|null;errorCode?:string|null;createdAt?:string;updatedAt?:string;steps?:unknown[];toolCalls?:unknown[];toolResults?:unknown[];metrics?:AgentRunMetrics}
export interface AgentRunEvent {sequence:number;type:string;payload:unknown;createdAt?:string}
export interface AgentRunEvents {runId:string|number;events:AgentRunEvent[];nextAfterSequence:number|null}
export interface CreateAgentRunInput {objective:string;constraints:string[];deliverables:string[];acceptanceChecks:string[];expectedContentRevision:number;idempotencyKey:string}
export interface RetryAgentRunInput {idempotencyKey?:string;expectedContentRevision?:number}
export interface Artifact {artifactId:string;workflowId:string;instanceId:string|null;runId:string|number|null;name:string;version:number;kind:string;mimeType:string;metadata:Record<string,unknown>;sha256:string;size:number;createdAt:string;content?:string}
export interface ComparisonBranch {instanceId:string;topicId:string;title:string;status:Status;memoryRoute:Array<{instanceId:string;title:string}>;localMessageCounts:Record<string,number>;latestRun:{runId:string|number;status:AgentRunStatus;objective:string;modelSnapshot:unknown;finalAnswer:string|null;errorCode:string|null;createdAt:string}|null;artifacts:Artifact[]}
export interface BranchComparison {workflowId:string;instanceIds:string[];sharedRoute:Array<{instanceId:string;title:string}>;branches:ComparisonBranch[];transcriptsIncluded:false}
export interface DatasetCase {id:string;input:string;expected?:string|null;tags:string[]}
export interface Dataset {datasetId:string;workflowId:string;name:string;version:number;description:string;sha256:string;caseCount:number;createdAt:string;cases?:DatasetCase[]}
export interface Experiment {experimentId:string;workflowId:string;name:string;datasetId:string;instanceIds:string[];runIds:Array<string|number>;metric:string;notes:string;snapshot:{dataset:{datasetId:string;name:string;version:number;sha256:string};instances:Array<{instanceId:string;route:string[]}>;runs:Array<{runId:string|number;instanceId:string;status:AgentRunStatus;objective:string;modelSnapshot:unknown;finalAnswer:string|null;errorCode:string|null}>};createdAt:string}
