import{useCallback,useEffect,useMemo,useRef,useState}from'react';
import type{AIStatus,Graph,Message,WorkflowSummary}from'../domain/types';import{api,ApiError}from'../lib/api';import{useI18n}from'../lib/i18n';import{routeLabel}from'../domain/graph';import{LanguageSelect}from'../components/LanguageSelect';import{ErrorBanner}from'../components/ErrorBanner';import{ModelSettingsDialog}from'../components/ModelSettingsDialog';import{MarkdownMessage}from'../components/MarkdownMessage';
type ReplyState='idle'|'thinking'|'error';
export function ChatPage(){
 const{t}=useI18n();const[settingsOpen,setSettingsOpen]=useState(false),[workflows,setWorkflows]=useState<WorkflowSummary[]>([]),[workflowId,setWorkflowId]=useState(localStorage.getItem('cw.workflow')||''),[graph,setGraph]=useState<Graph|null>(null),[messages,setMessages]=useState<Message[]>([]),[inherited,setInherited]=useState<Message[]>([]),[memoryOpen,setMemoryOpen]=useState(false),[memoryLoading,setMemoryLoading]=useState(false),[draft,setDraft]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[creating,setCreating]=useState(false),[newName,setNewName]=useState(''),[rootTitle,setRootTitle]=useState(''),[aiStatus,setAiStatus]=useState<AIStatus|null>(null),[replyState,setReplyState]=useState<ReplyState>('idle'),[replyError,setReplyError]=useState('');
 const[editingId,setEditingId]=useState(''),[editDraft,setEditDraft]=useState(''),[copiedId,setCopiedId]=useState(''),[nodeRevision,setNodeRevision]=useState(0);const revisionRef=useRef(0);revisionRef.current=nodeRevision;
 const messagesRef=useRef<HTMLDivElement>(null),graphRequest=useRef(0),messageRequest=useRef(0),memoryRequest=useRef(0),sendLocks=useRef<Set<string>>(new Set()),activeKey=useRef('');const active=useMemo(()=>graph?.nodes.find(n=>n.id===graph.activeInstanceId),[graph]);activeKey.current=graph?.activeInstanceId?`${graph.workflowId}:${graph.activeInstanceId}`:'';
 const refreshAI=useCallback(async()=>{try{setAiStatus(await api.aiStatus())}catch(e){setError(e instanceof Error?e.message:String(e))}},[]);
 const loadWorkflows=useCallback(async()=>{try{const list=await api.workflows();setWorkflows(list);if(!list.some(w=>w.id===workflowId)){const next=list[0]?.id||'';setWorkflowId(next);setGraph(null);setMessages([]);setError('');if(!next)localStorage.removeItem('cw.workflow')}}catch(e){setError(e instanceof Error?e.message:String(e))}},[workflowId]);
 const loadGraph=useCallback(async()=>{const request=++graphRequest.current;if(!workflowId){setGraph(null);setMessages([]);return}try{const g=await api.graph(workflowId);if(request!==graphRequest.current)return;setGraph(g);setError('');localStorage.setItem('cw.workflow',workflowId)}catch(e){if(request!==graphRequest.current)return;if(e instanceof ApiError&&e.status===404){localStorage.removeItem('cw.workflow');setWorkflowId('');setGraph(null);setMessages([]);setError('');return}setError(e instanceof Error?e.message:String(e))}},[workflowId]);
 useEffect(()=>{void loadWorkflows();void refreshAI()},[loadWorkflows,refreshAI]);useEffect(()=>{setGraph(null);setMessages([]);graphRequest.current++;void loadGraph()},[loadGraph]);
 useEffect(()=>{const request=++messageRequest.current;memoryRequest.current++;setMessages([]);setInherited([]);setMemoryOpen(false);setMemoryLoading(false);setReplyState('idle');setReplyError('');setBusy(false);setEditingId('');setEditDraft('');setCopiedId('');setNodeRevision(active?.contentRevision||0);const workflow=graph?.workflowId,instance=graph?.activeInstanceId;if(!workflow||!instance)return;api.messageSnapshot(workflow,instance,'local').then(value=>{if(request===messageRequest.current&&activeKey.current===`${workflow}:${instance}`){setMessages(value.messages);setNodeRevision(value.contentRevision)}}).catch(e=>{if(request===messageRequest.current)setError(e.message)})},[graph?.workflowId,graph?.activeInstanceId]);
 useEffect(()=>{const box=messagesRef.current;if(box)box.scrollTop=box.scrollHeight},[messages,replyState]);useEffect(()=>{const refresh=()=>void loadGraph();const channel=new BroadcastChannel('conversation-workflow');channel.addEventListener('message',refresh);const receive=(event:MessageEvent)=>{if(event.data?.type==='conversation-workflow-changed')refresh()};window.addEventListener('message',receive);return()=>{channel.close();window.removeEventListener('message',receive)}},[loadGraph]);
 async function toggleMemory(){const opening=!memoryOpen;setMemoryOpen(opening);if(!opening||inherited.length||memoryLoading)return;const workflow=graph?.workflowId,instance=graph?.activeInstanceId;if(!workflow||!instance)return;const request=++memoryRequest.current,key=`${workflow}:${instance}`;setMemoryLoading(true);try{const value=await api.messages(workflow,instance,'effective');if(request===memoryRequest.current&&activeKey.current===key)setInherited(value.filter(m=>m.inherited))}catch(e){if(request===memoryRequest.current)setError(e instanceof Error?e.message:String(e))}finally{if(request===memoryRequest.current&&activeKey.current===key)setMemoryLoading(false)}}
 async function create(){if(!newName.trim()||!rootTitle.trim())return;setBusy(true);try{const w=await api.createWorkflow({name:newName.trim(),rootTitle:rootTitle.trim(),rootTopicId:crypto.randomUUID()});setCreating(false);setWorkflowId(w.workflowId);await loadWorkflows()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 function aiError(e:unknown){if(e instanceof ApiError){switch(e.code){case'aiTimeout':return t('aiTimeout');case'aiUnavailable':return t('aiUnavailable');case'aiEmptyResponse':return t('aiEmptyResponse');case'validationError':return t('validationError');case'conflict':return t('contentConflict')}}return t('aiGenericError')}
 function beginEdit(message:Message){setEditingId(String(message.id));setEditDraft(message.content)}
 async function copyMessage(message:Message){try{await navigator.clipboard.writeText(message.content);setCopiedId(String(message.id))}catch{setCopiedId('')}}
 async function regenerate(message:Message){const content=editDraft.trim(),workflow=graph?.workflowId,instance=graph?.activeInstanceId;if(!content||!workflow||!instance)return;const key=`${workflow}:${instance}`,expected=nodeRevision;if(sendLocks.current.has(key))return;sendLocks.current.add(key);setBusy(true);setEditingId('');setReplyError('');if(aiStatus?.configured)setReplyState('thinking');try{const value=await api.regenerate(workflow,instance,message.id,content,expected);if(activeKey.current===key&&revisionRef.current===expected){setMessages(value.messages);setNodeRevision(value.contentRevision);setReplyState('idle')}}catch(e){if(activeKey.current===key&&revisionRef.current===expected){setReplyError(aiError(e));setReplyState('error')}}finally{sendLocks.current.delete(key);if(activeKey.current===key)setBusy(false)}}
 async function send(){const text=draft.trim(),workflow=graph?.workflowId,instance=graph?.activeInstanceId;if(!text||!workflow||!instance)return;const key=`${workflow}:${instance}`;if(sendLocks.current.has(key))return;sendLocks.current.add(key);setDraft('');setBusy(true);setError('');setReplyError('');setMessages(x=>[...x,{id:crypto.randomUUID(),role:'user',content:text,inherited:false}]);const expectsAI=!!aiStatus?.configured;if(expectsAI)setReplyState('thinking');try{if(expectsAI)await api.chat(workflow,instance,text);else await api.send(workflow,instance,text);const value=await api.messageSnapshot(workflow,instance,'local');if(activeKey.current===key){setMessages(value.messages);setNodeRevision(value.contentRevision);setReplyState('idle')}}catch(e){if(activeKey.current===key){setReplyError(aiError(e));setReplyState('error');try{const value=await api.messageSnapshot(workflow,instance,'local');setMessages(value.messages);setNodeRevision(value.contentRevision)}catch{}}}finally{sendLocks.current.delete(key);if(activeKey.current===key)setBusy(false)}}
 function openGraph(){if(!graph)return;const url=new URL('/graph',window.location.href);url.searchParams.set('workflow',graph.workflowId);const popup=window.open(url.href,'_blank','popup=yes,width=1280,height=820,resizable=yes');if(popup){try{popup.location.replace(url.href);popup.focus()}catch{}}else window.location.assign(url.href)}
 const lastUserId=([...messages].reverse().find(m=>m.role==='user'&&!m.inherited)?.id);const renderMessage=(m:Message,actions=false)=><article key={m.id} className={`message ${m.role}${actions&&m.id===lastUserId?' actionable':''}`}><div>{editingId===String(m.id)?<div className="message-edit"><label>{t('editQuestionLabel')}<textarea value={editDraft} onChange={e=>setEditDraft(e.target.value)}/></label><div><button type="button" onClick={()=>{setEditingId('');setEditDraft('')}}>{t('cancelEdit')}</button><button type="button" className="primary" disabled={!editDraft.trim()||busy} onClick={()=>void regenerate(m)}>{t('saveRegenerate')}</button></div></div>:<>{m.role==='assistant'?<MarkdownMessage content={m.content}/>:m.content}{actions&&m.id===lastUserId&&<div className="message-actions"><button type="button" onClick={()=>beginEdit(m)}>{t('editQuestion')}</button><button type="button" onClick={()=>void copyMessage(m)}>{copiedId===String(m.id)?t('copied'):t('copyMessage')}</button></div>}</>}</div></article>;const memoryPanel=active?.parentId?<section className="inherited-memory"><button type="button" aria-expanded={memoryOpen} onClick={()=>void toggleMemory()}><span>{memoryOpen?'▾':'▸'} {t('inheritedMemory')}</span></button>{memoryOpen&&<div className="inherited-memory-body">{memoryLoading?<p>{t('loadingInherited')}</p>:inherited.length?inherited.map(m=>renderMessage(m)):<p>{t('noInherited')}</p>}</div>}</section>:null;const stream=<div className="messages" ref={messagesRef}>{memoryPanel}{!messages.length&&replyState==='idle'&&<p className="empty">{workflowId?t('empty'):t('selectWorkflow')}</p>}{messages.map(m=>renderMessage(m,true))}{replyState==='thinking'&&<article className="message assistant reply-thinking" aria-live="polite"><div><span>{t('thinking')}</span><span className="thinking-dots" aria-hidden="true"><i/><i/><i/></span></div></article>}{replyState==='error'&&<article className="message system reply-error" role="alert"><div>{replyError}</div></article>}</div>;
 return <main className="chat-shell"><aside className="sidebar"><div className="brand">◫ <strong>{t('app')}</strong></div><button className="new-workflow" onClick={()=>setCreating(true)}>＋ {t('newWorkflow')}</button><h2>{t('conversations')}</h2><nav>{workflows.map(w=><button className={w.id===workflowId?'current':''} key={w.id} onClick={()=>setWorkflowId(w.id)}>{w.name}</button>)}</nav><div className="sidebar-controls"><button className="settings-button" onClick={()=>setSettingsOpen(true)}>⚙ {t('settings')}</button><LanguageSelect/></div></aside><section className="chat"><header><div><h1>{active?.title||graph?.name||t('app')}</h1><p>{t('route')}: {graph&&active?routeLabel(graph,active.id):'—'}</p><span className={`ai-status ${aiStatus?.configured?'connected':'local'}`}>{aiStatus?.configured?`${t('aiConnected')} · ${aiStatus.model}`:t('recordOnly')}</span></div><button className="workflow-launch" disabled={!graph} onClick={openGraph}>⌘ {t('workflow')}</button></header><ErrorBanner message={error} onRetry={()=>{setError('');void loadGraph()}}/>{stream}<form className="composer" onSubmit={e=>{e.preventDefault();void send()}}><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder={t('placeholder')} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}}/><button className="primary" disabled={!draft.trim()||busy}>{t('send')}</button></form></section>{settingsOpen&&<ModelSettingsDialog onClose={()=>setSettingsOpen(false)} onSaved={refreshAI}/>} {creating&&<div className="modal-backdrop"><form className="modal" onSubmit={e=>{e.preventDefault();void create()}}><h2>{t('newWorkflow')}</h2><label>{t('workflowName')}<input autoFocus required value={newName} onChange={e=>setNewName(e.target.value)}/></label><label>{t('rootTitle')}<input required value={rootTitle} onChange={e=>setRootTitle(e.target.value)}/></label><div className="modal-actions"><button type="button" onClick={()=>setCreating(false)}>{t('cancel')}</button><button className="primary" disabled={busy}>{t('createOpen')}</button></div></form></div>}</main>
}
