import{useCallback,useEffect,useMemo,useState}from'react';
import type{Graph,PrunePlan,Route}from'../domain/types';
import{api}from'../lib/api';import{useI18n}from'../lib/i18n';import{notifyWorkflowChanged}from'../lib/workflowEvents';import{routeLabel}from'../domain/graph';
import{WorkflowGraph,useClickArbitration}from'../components/WorkflowGraph';import{BranchDialog}from'../components/BranchDialog';import{PruneDialog}from'../components/PruneDialog';import{LanguageSelect}from'../components/LanguageSelect';import{ErrorBanner}from'../components/ErrorBanner';
function RouteChoice({route,label,selected,onSelect,onActivate}:{route:Route;label:string;selected:boolean;onSelect:()=>void;onActivate:()=>void}){const events=useClickArbitration(onSelect,onActivate);return <button className={selected?'current':''}{...events}>{label}</button>}
export function GraphPage(){
 const{t}=useI18n();const workflowId=new URLSearchParams(location.search).get('workflow')||localStorage.getItem('cw.workflow')||'';
 const[graph,setGraph]=useState<Graph|null>(null),[selected,setSelected]=useState(''),[routes,setRoutes]=useState<Route[]>([]),[branch,setBranch]=useState(false),[plan,setPlan]=useState<PrunePlan|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const node=useMemo(()=>graph?.nodes.find(n=>n.id===selected),[graph,selected]);
 const load=useCallback(async()=>{if(!workflowId)return;try{const g=await api.graph(workflowId);setGraph(g);setSelected(s=>g.nodes.some(n=>n.id===s)?s:(g.activeInstanceId||g.rootInstanceId))}catch(e){setError(e instanceof Error?e.message:String(e))}},[workflowId]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(!node||!graph)return;api.routes(graph.workflowId,node.topicId).then(setRoutes).catch(e=>setError(e.message))},[node?.id,node?.topicId,graph?.workflowId]);
 const activate=useCallback(async(id:string)=>{if(!graph||busy)return;setBusy(true);setError('');try{const r=await api.activate(graph.workflowId,id);if(r.activeInstanceId!==id)throw Error(t('failed'));notifyWorkflowChanged({type:'conversation-workflow-changed',workflowId:graph.workflowId,instanceId:id});window.close()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}},[graph,busy,t]);
 async function fork(input:{title:string;topicId?:string;initialMessage?:string}){if(!graph||!node)return;setBusy(true);try{const result=await api.fork(graph.workflowId,node.id,input);setBranch(false);await load();await activate(result.node.id)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function preparePrune(){if(!graph||!node)return;setBusy(true);try{setPlan(await api.prunePlan(graph.workflowId,node.id,node.id===graph.rootInstanceId))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function commitPrune(){if(!graph||!node||!plan)return;setBusy(true);try{const result=await api.pruneCommit(graph.workflowId,node.id,plan);setPlan(null);notifyWorkflowChanged({type:'conversation-workflow-changed',workflowId:graph.workflowId,...(result.activeInstanceId?{instanceId:result.activeInstanceId}:{})});await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const routeText=(route:Route)=>route.memoryRoute.map(id=>graph?.nodes.find(n=>n.id===id)?.title||id).join(' → ');
 if(!graph)return <div className="loading"><ErrorBanner message={error} onRetry={()=>void load()}/>{error?'':t('loading')}</div>;
 return <main className="graph-page"><header className="graph-header"><div><h1>{graph.name}</h1><p>{t('doubleClick')}</p></div><LanguageSelect/><button onClick={()=>window.close()}>{t('close')}</button></header><ErrorBanner message={error} onRetry={()=>{setError('');void load()}}/><section className="graph-body"><div className="graph-canvas"><WorkflowGraph graph={graph} selectedId={selected} onSelect={setSelected} onActivate={activate}/></div><aside className="inspector"><h2>{t('details')}</h2>{node&&<><h3>{node.title}</h3><p>{node.summary||'—'}</p><small>{t('route')}</small><p>{routeLabel(graph,node.id)}</p><h3>{t('routes')}</h3><div className="route-list">{routes.length?routes.map(r=><RouteChoice key={r.id} route={r} label={routeText(r)} selected={r.id===selected} onSelect={()=>setSelected(r.id)} onActivate={()=>void activate(r.id)}/>):<p>{t('noRoutes')}</p>}</div><div className="inspector-actions"><button className="primary" disabled={busy||node.status==='pruned'} onClick={()=>void activate(node.id)}>{t('activate')}</button><button disabled={busy||node.status==='pruned'} onClick={()=>setBranch(true)}>{t('branch')}</button><button className="danger-outline" disabled={busy||node.status==='pruned'} onClick={()=>void preparePrune()}>{t('archive')}</button></div></>}</aside></section><BranchDialog open={branch} parentTitle={node?.title||''} busy={busy} onClose={()=>setBranch(false)} onSubmit={x=>void fork(x)}/><PruneDialog plan={plan} busy={busy} onClose={()=>setPlan(null)} onCommit={()=>void commitPrune()}/></main>
}
