import {createContext,useContext,useMemo,useState,type ReactNode} from 'react';
export type Locale='zh-CN'|'en';
const copy={
 en:{app:'Conversation workflow',newWorkflow:'New workflow',workflowName:'Workflow name',rootTitle:'First conversation name',conversations:'Conversations',workflow:'Workflow',settings:'Settings',language:'Interface language',send:'Send',placeholder:'Message this route…',loading:'Loading…',retry:'Retry',empty:'No messages yet.',route:'Memory route',graph:'Conversation graph',fit:'Fit view',close:'Close',details:'Details',summary:'Summary',routes:'Topic routes',branch:'New branch',branchTitle:'Conversation name',topic:'Topic ID (optional)',firstMessage:'First message (optional)',createOpen:'Create and open',cancel:'Cancel',archive:'Cascade archive',archiveConfirm:'Archive selected branch?',archiveHint:'Descendant conversations are archived leaf-first; tombstones remain.',rootRisk:'I understand this archives the entire workflow, including its root.',confirm:'Confirm archive',activate:'Open conversation',doubleClick:'Double-click a node to open it',failed:'Operation failed',current:'Current',archived:'Archived',noRoutes:'No alternative routes.',selectWorkflow:'Select or create a workflow.',recordOnly:'Record-only mode · AI not connected',aiConnected:'AI configured',modelSettings:'Model settings',provider:'Provider preset',customProvider:'Custom / OpenAI-compatible',baseUrl:'Base URL',model:'Model',apiKey:'API key',keyRetained:'Saved key retained if left blank',keyOptional:'Optional for local providers',keyMemoryHint:'API keys stay in process memory only and are never stored locally.',timeout:'Timeout (seconds)',persistNonSecret:'Persist non-secret settings on this device',testFetch:'Test & fetch models',save:'Save',reset:'Reset',resetConfirm:'Reset model settings and return to record-only mode?',confirmReset:'Reset settings',connectionOk:'Connection successful. Models loaded.',connectionOkModelMissing:'Connected, but the selected model was not listed.',connectionFailed:'Connection failed'},
 'zh-CN':{app:'对话工作流',newWorkflow:'新建工作流',workflowName:'工作流名称',rootTitle:'起始对话名称',conversations:'对话',workflow:'工作流',settings:'设置',language:'界面语言',send:'发送',placeholder:'在这条记忆路线中发送消息…',loading:'正在加载…',retry:'重试',empty:'暂无消息。',route:'记忆路线',graph:'对话流程图',fit:'适应画布',close:'关闭',details:'详情',summary:'摘要',routes:'同主题路线',branch:'新建分支',branchTitle:'对话名称',topic:'主题 ID（可选）',firstMessage:'首条消息（可选）',createOpen:'创建并打开',cancel:'取消',archive:'级联归档',archiveConfirm:'归档所选分支？',archiveHint:'后代对话将按叶节点优先归档，并保留墓碑。',rootRisk:'我已了解这会归档包含根节点在内的整个工作流。',confirm:'确认归档',activate:'打开对话',doubleClick:'双击节点打开对话',failed:'操作失败',current:'当前',archived:'已归档',noRoutes:'没有其他路线。',selectWorkflow:'请选择或创建一个工作流。',recordOnly:'仅记录模式 · 尚未连接 AI',aiConnected:'AI 已配置',modelSettings:'模型设置',provider:'服务商预设',customProvider:'自定义 / OpenAI 兼容',baseUrl:'基础地址',model:'模型',apiKey:'API 密钥',keyRetained:'留空将保留已有密钥',keyOptional:'本地模型可不填写',keyMemoryHint:'API 密钥仅保存在当前服务进程内，绝不会写入本地配置。',timeout:'超时（秒）',persistNonSecret:'在本机保存非敏感设置',testFetch:'测试并获取模型',save:'保存',reset:'重置',resetConfirm:'重置模型设置并返回仅记录模式？',confirmReset:'确认重置',connectionOk:'连接成功，已加载模型列表。',connectionOkModelMissing:'连接成功，但列表中没有当前模型。',connectionFailed:'连接失败'}
}as const;
const replyCopy={en:{thinking:'Thinking',aiTimeout:'The model response timed out. Please try again.',aiUnavailable:'The AI service is unavailable. Check model settings and try again.',aiEmptyResponse:'The model returned an empty response.',validationError:'The message or model configuration is invalid.',contentConflict:'This conversation changed while you were editing. Open Edit and try again.',aiGenericError:'The AI request failed. Please try again.'},'zh-CN':{thinking:'正在思考',aiTimeout:'模型响应超时，请重试。',aiUnavailable:'AI 服务不可用，请检查模型设置后重试。',aiEmptyResponse:'模型返回了空响应。',validationError:'消息或模型配置无效。',contentConflict:'编辑期间对话已发生变化，请重新打开编辑后再试。',aiGenericError:'AI 请求失败，请重试。'}}as const;
const memoryCopy={en:{inheritedMemory:'Inherited route memory',loadInherited:'Load inherited memory',loadingInherited:'Loading inherited memory…',noInherited:'No inherited messages on this route.'},'zh-CN':{inheritedMemory:'继承的路线记忆',loadInherited:'加载继承记忆',loadingInherited:'正在加载继承记忆…',noInherited:'这条路线没有继承消息。'}}as const;
const actionCopy={en:{editQuestion:'Edit',copyMessage:'Copy',copied:'Copied',cancelEdit:'Cancel',saveRegenerate:'Save & regenerate',editQuestionLabel:'Edit your question'},'zh-CN':{editQuestion:'编辑',copyMessage:'复制',copied:'已复制',cancelEdit:'取消',saveRegenerate:'保存并重新生成',editQuestionLabel:'编辑你的提问'}}as const;
type Key=keyof typeof copy.en|keyof typeof replyCopy.en|keyof typeof memoryCopy.en|keyof typeof actionCopy.en;const C=createContext<{locale:Locale;setLocale:(x:Locale)=>void;t:(k:Key)=>string}|null>(null);
export function I18nProvider({children}:{children:ReactNode}){const[locale,setLocaleState]=useState<Locale>(()=>(localStorage.getItem('cw.locale')as Locale)||'zh-CN');const value=useMemo(()=>({locale,setLocale:(x:Locale)=>{localStorage.setItem('cw.locale',x);setLocaleState(x)},t:(k:Key)=>k==='app'?'WeavePath':k in replyCopy.en?replyCopy[locale][k as keyof typeof replyCopy.en]:k in memoryCopy.en?memoryCopy[locale][k as keyof typeof memoryCopy.en]:k in actionCopy.en?actionCopy[locale][k as keyof typeof actionCopy.en]:copy[locale][k as keyof typeof copy.en]}),[locale]);return <C.Provider value={value}>{children}</C.Provider>}
export function useI18n(){const x=useContext(C);if(!x)throw Error('I18nProvider missing');return x}
